frontend-base:
    path: /
    controller: App\Controller\AppController::frontend
    methods: GET|HEAD
frontend:
    path: /{path}
    controller: App\Controller\AppController::frontend
    methods: GET|HEAD
    requirements:
        path: login
backend:
    path: /{path}
    controller: App\Controller\AppController::backend
    methods: GET|HEAD
    requirements:
        path: "^(?!login).+"
