frontend-base:
    path: /
    controller: App\Controller\AppController::frontend
    methods: GET|HEAD
frontend:
    path: /{path}
    controller: App\Controller\AppController::frontend
    methods: GET|HEAD
    requirements:
        path: login|interests

app_logout:
    path: /logout
    methods: GET

statusCheck:
    path: /check-ticket/{token}
    controller: App\Controller\AppController::checkStatus
    methods: GET|HEAD

backend:
    path: /{path}
    controller: App\Controller\AppController::backend
    methods: GET|HEAD
    requirements:
        path: "^(?!login|api|logout).+"
